# Generated by Django 4.1.2 on 2022-11-18 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('doctormobile', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='newpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newpatientname', models.CharField(max_length=100)),
                ('patientmobile', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patientdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=100)),
                ('patienttreatment', models.CharField(max_length=100)),
                ('patientdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
