# Generated by Django 4.1.2 on 2022-11-18 16:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctordetails_doctormobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='patientmobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
