# Generated by Django 4.1.2 on 2022-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctordetails_doctormobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='doctormobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='patientmobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
